# Certificate Authority Configuration
# This file configures the settings for generating a CA certificate

# Certificate Type (root, intermediate)
# root: Self-signed root certificate (requires Class 2 or higher)
# intermediate: CA certificate signed by another CA
type: root

# Certificate Class (1-3)
# 1: Low-assurance (email, personal use)
# 2: Medium-assurance (organization validation)
# 3: High-assurance (extended validation)
class: 2

# Basic Information
commonName: "Example Root CA"
organization: "Example Organization"
organizationalUnit: "IT Department"
country: "US"
province: "California"
locality: "San Francisco"

# Certificate Settings
# For root certificates:
# - Key size must be at least 4096 bits
# - Validity should be at least 5 years
validityDays: 3650  # 10 years
keySize: 4096       # Minimum for root certificates

# Output Directory
outputDir: "certs"

# Optional: Disable progress display
# noProgress: false

# Class 3 CA Configuration
class3: false  # Enable Class 3 CA features
crlDistributionPoints:
  - "http://crl.example.com/root.crl"
ocspServers:
  - "http://ocsp.example.com"
issuingCertificateUrls:
  - "http://example.com/ca.crt" 