# Certificate Authority Configuration
# This file configures the settings for generating a CA certificate

# Certificate type (0: Root, 1: Intermediate)
type: 0  # 0 for Root, 1 for Intermediate

# Certificate Class (1-3)
# 1: Low-assurance (email, personal use)
# 2: Medium-assurance (organization validation)
# 3: High-assurance (extended validation)
class: 3  # Required for root certificates to satisfy validity requirements

# Basic Information
commonName: "Trusted Local Class III Root CA"
organization: "Trusted Development"
organizationalUnit: "Security"
country: "US"
province: "Texas"
locality: "Starbase"

# Certificate Settings
# For root certificates:
# - Key size must be at least 4096 bits
# - Validity should be at least 5 years
validityDays: 3650  # 10 years (minimum 5 years for root)
keySize: 4096       # Minimum for root certificates

# Output Directory
outputDir: "certs"

# Optional: Disable progress display
# noProgress: false

# Class 3 CA Configuration
class3: false  # Enable Class 3 CA features
crlDistributionPoints:
  - "http://crl.example.com/root.crl"
ocspServers:
  - "http://ocsp.example.com"
issuingCertificateUrls:
  - "http://example.com/ca.crt" 