# Server/Client Certificate Configuration
# This file configures the settings for generating a certificate

# Certificate Class (1-3)
# 1: Low-assurance (email, personal use)
# 2: Medium-assurance (organization validation)
# 3: High-assurance (extended validation)
class: 2

# Basic Information
commonName: "example.com"
organization: "Example Organization"
organizationalUnit: "Web Services"
country: "US"
province: "Texas"
locality: "Starbase"

# Certificate Settings
# Validity period in days (class-dependent maximums)
validityDays: 365  # 1 year
keySize: 3072      # Minimum for Class 2

# DNS Names for the certificate
# Include all domains and subdomains that this certificate will be used for
dnsNames:
  - "example.com"
  - "*.example.com"
  - "www.example.com"

# CA Signing Information
# Path to the CA certificate and private key
caCert: "certs/ca.crt"
caKey: "certs/ca.key"

# Output Directory
outputDir: "certs"

# Optional: Disable progress display
# noProgress: false 